# Mã code exit
Mã code exit, còn được gọi là "mã trả về" hoặc "mã trạng thái", là các giá trị số mà chương trình trả về môi trường gọi (thường là hệ điều hành) khi chương trình kết thúc thực thi. Các mã code này được sử dụng để chỉ ra sự thành công hay thất bại của việc thực hiện chương trình.

0 là mã thoát tiêu chuẩn để thực thi thành công, trong khi các mã code thoát khác 0 thường biểu thị lỗi hoặc các tình huống ngoại lệ khác. Ý nghĩa thực tế của các mã  code thoát khác không có thể khác nhau giữa các ứng dụng hoặc hệ thống khác nhau.
Trong C++, bạn có thể trả về mã code thoát từ hàm main bằng cách sử dụng câu lệnh return hoặc bạn có thể sử dụng hàm exit(), là một phần của Thư viện chuẩn C++.

## Ví dụ: Sử dụng return trong main
~~~
#include <iostream>

int main() {
    // một số mã code ở đây...

    if (/*some error condition*/) {
        std::cout << "An error occurred." << std::endl;
        return 1;
    }

    // một số mã code ở đây...

    if (/*another error condition*/) {
        std::cout << "Another error occurred." << std::endl;
        return 2;
    }

    return 0; // Thực hiện thành công
}
~~~
## Ví dụ: Sử dụng hàm exit()
~~~
#include <iostream>
#include <cstdlib>

void some_function() {
    // một số mã code ở đây...

    if (/*some error condition*/) {
        std::cout << "An error occurred." << std::endl;
        std::exit(1);
    }

    // một số  mã code ở đây...
}

int main() {
    some_function();

    // một số mã code khác ở đây...

    return 0; // thực hiện thành công 
}
~~~
Trong cả hai ví dụ trên, chương trình trả về các mã code thoát tùy thuộc vào các điều kiện lỗi khác nhau gặp phải trong quá trình thực thi. Mã code 1 và 2 được sử dụng để phân biệt giữa hai tình trạng lỗi.